# Generated by Django 5.0.1 on 2024-02-06 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('case_material', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('black', 'Черный'), ('white', 'Белый'), ('blue', 'Синий'), ('red', 'Красный'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('purple', 'Фиолетовый'), ('orange', 'Оранжевый'), ('brown', 'Коричневый'), ('gray', 'Серый'), ('pink', 'Розовый'), ('gold', 'Золотой'), ('silver', 'Серебряный'), ('platinum', 'Платиновый')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateField()),
                ('base_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('movement', models.CharField(choices=[('quartz', 'Кварц'), ('automatic', 'Автоматический'), ('solar', 'Солнечный'), ('mechanic', 'Механический')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.watch')),
            ],
        ),
    ]
