# Generated by Django 5.0.1 on 2024-02-06 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужские'), ('female', 'Женские')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchimage',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.watch'),
        ),
    ]
