# Generated by Django 5.0.1 on 2024-02-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_watch_gender_alter_watchimage_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужские'), ('female', 'Женские')], default='male', max_length=50),
        ),
    ]
