# Generated by Django 5.0.1 on 2024-02-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_watch_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужские'), ('female', 'Женские'), ('elect', 'Электронные')], default='male', max_length=50),
        ),
    ]
